//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReserve
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> Penalty { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
